convert slowEnemy.png -distort SRT 0 slowEnemy0.png
convert slowEnemy.png -distort SRT 6 slowEnemy1.png
convert slowEnemy.png -distort SRT 12 slowEnemy2.png
convert slowEnemy.png -distort SRT 18 slowEnemy3.png
convert slowEnemy.png -distort SRT 24 slowEnemy4.png
convert slowEnemy.png -distort SRT 30 slowEnemy5.png
convert slowEnemy.png -distort SRT 36 slowEnemy6.png
convert slowEnemy.png -distort SRT 42 slowEnemy7.png
convert slowEnemy.png -distort SRT 48 slowEnemy8.png
convert slowEnemy.png -distort SRT 54 slowEnemy9.png
convert slowEnemy.png -distort SRT 60 slowEnemy10.png
convert slowEnemy.png -distort SRT 66 slowEnemy11.png
convert slowEnemy.png -distort SRT 72 slowEnemy12.png
convert slowEnemy.png -distort SRT 78 slowEnemy13.png
convert slowEnemy.png -distort SRT 84 slowEnemy14.png
convert slowEnemy.png -distort SRT 90 slowEnemy15.png
convert slowEnemy.png -distort SRT 96 slowEnemy16.png
convert slowEnemy.png -distort SRT 102 slowEnemy17.png
convert slowEnemy.png -distort SRT 108 slowEnemy18.png
convert slowEnemy.png -distort SRT 114 slowEnemy19.png
convert slowEnemy.png -distort SRT 120 slowEnemy20.png
convert slowEnemy.png -distort SRT 126 slowEnemy21.png
convert slowEnemy.png -distort SRT 132 slowEnemy22.png
convert slowEnemy.png -distort SRT 138 slowEnemy23.png
convert slowEnemy.png -distort SRT 144 slowEnemy24.png
convert slowEnemy.png -distort SRT 150 slowEnemy25.png
convert slowEnemy.png -distort SRT 156 slowEnemy26.png
convert slowEnemy.png -distort SRT 162 slowEnemy27.png
convert slowEnemy.png -distort SRT 168 slowEnemy28.png
convert slowEnemy.png -distort SRT 174 slowEnemy29.png
convert slowEnemy.png -distort SRT 180 slowEnemy30.png
convert slowEnemy.png -distort SRT 186 slowEnemy31.png
convert slowEnemy.png -distort SRT 192 slowEnemy32.png
convert slowEnemy.png -distort SRT 198 slowEnemy33.png
convert slowEnemy.png -distort SRT 204 slowEnemy34.png
convert slowEnemy.png -distort SRT 210 slowEnemy35.png
convert slowEnemy.png -distort SRT 216 slowEnemy36.png
convert slowEnemy.png -distort SRT 222 slowEnemy37.png
convert slowEnemy.png -distort SRT 228 slowEnemy38.png
convert slowEnemy.png -distort SRT 234 slowEnemy39.png
convert slowEnemy.png -distort SRT 240 slowEnemy40.png
convert slowEnemy.png -distort SRT 246 slowEnemy41.png
convert slowEnemy.png -distort SRT 252 slowEnemy42.png
convert slowEnemy.png -distort SRT 258 slowEnemy43.png
convert slowEnemy.png -distort SRT 264 slowEnemy44.png
convert slowEnemy.png -distort SRT 270 slowEnemy45.png
convert slowEnemy.png -distort SRT 276 slowEnemy46.png
convert slowEnemy.png -distort SRT 282 slowEnemy47.png
convert slowEnemy.png -distort SRT 288 slowEnemy48.png
convert slowEnemy.png -distort SRT 294 slowEnemy49.png
convert slowEnemy.png -distort SRT 300 slowEnemy50.png
convert slowEnemy.png -distort SRT 306 slowEnemy51.png
convert slowEnemy.png -distort SRT 312 slowEnemy52.png
convert slowEnemy.png -distort SRT 318 slowEnemy53.png
convert slowEnemy.png -distort SRT 324 slowEnemy54.png
convert slowEnemy.png -distort SRT 330 slowEnemy55.png
convert slowEnemy.png -distort SRT 336 slowEnemy56.png
convert slowEnemy.png -distort SRT 342 slowEnemy57.png
convert slowEnemy.png -distort SRT 348 slowEnemy58.png
convert slowEnemy.png -distort SRT 354 slowEnemy59.png