#ifndef GooglePlayGamesUnityPlugin_GPGSParams_h
#define GooglePlayGamesUnityPlugin_GPGSParams_h

// DO NOT EDIT THIS FILE. It is automatically generated by the Google Play Games
// Unity plugin and will be overwritten.

/*
  This section exists for the benefit of shell scripts (in particular,
  the post-processing script) that need to get information from this
  file:

AppId=188355348585
BundleId=com.moonlightgames.vectorswarm
ClientId=46798138751-afwa4iejsfjskj.apps.googleusercontent.com

*/

#define kAppID "188355348585"
#define kBundleID "com.moonlightgames.vectorswarm"
#define kClientID "46798138751-afwa4iejsfjskj.apps.googleusercontent.com"

#endif


